name: Ежедневная генерация и публикация поста

on:
  schedule:
    - cron: "0 9 * * *"  # Каждый день в 9:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Установить зависимости
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Сгенерировать пост от ИИ
        env:
          DASHSCOPE_API_KEY: ${{ secrets.DASHSCOPE_API_KEY }}
        run: |
          python generate_post.py

      - name: Опубликовать пост в Telegram
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          python main.py
